In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset['charges']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [12]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.047537,0.010698,0.013350,0.001850,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.004176,0.022594,-0.118956,-0.082926,-0.103473,-0.057387,0.056205,35
1,0.027994,0.008407,0.003643,0.001120,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.047420,0.077536,-0.060527,-0.009476,-0.050823,0.000826,0.054025,32
2,0.031152,0.006075,0.007316,0.001590,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.044787,0.081689,-0.072355,-0.027541,-0.051470,-0.004978,0.058648,34
3,0.020769,0.004569,0.004284,0.000904,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.387624,0.461268,0.288301,0.340540,0.297825,0.355112,0.063693,25
4,0.027115,0.001456,0.015551,0.001503,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.003956,0.022453,-0.119035,-0.082925,-0.103510,-0.057395,0.056230,36
5,0.022498,0.005321,0.004912,0.001362,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.043648,0.079780,-0.059229,-0.009498,-0.050317,0.000877,0.053658,31
6,0.035728,0.008079,0.007424,0.000919,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.043946,0.082230,-0.072132,-0.027546,-0.051337,-0.004968,0.058595,33
7,0.018476,0.004834,0.003653,0.001090,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.387624,0.461268,0.288301,0.340540,0.297825,0.355112,0.063693,25
8,0.027007,0.004563,0.013925,0.002288,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.303414,0.319385,0.155546,0.208414,0.161756,0.229703,0.069348,29
9,0.022171,0.001149,0.004989,0.000819,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.542212,0.566743,0.471172,0.537557,0.413719,0.506281,0.056081,22
10,0.037924,0.003526,0.008046,0.001106,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.492088,0.545107,0.438714,0.468576,0.425516,0.474000,0.042447,23
11,0.028946,0.003890,0.004909,0.001170,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.596232,0.635776,0.566816,0.588799,0.537415,0.585008,0.032600,19
12,0.028293,0.001855,0.014280,0.000990,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.304939,0.318480,0.155033,0.208422,0.161488,0.229672,0.069604,30
13,0.024176,0.002059,0.005368,0.001499,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.532310,0.571466,0.474948,0.537506,0.415264,0.506299,0.055077,21
14,0.037161,0.002421,0.007312,0.000876,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.491855,0.544604,0.439299,0.468556,0.424226,0.473708,0.042461,24
15,0.028337,0.003124,0.004457,0.000776,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.596232,0.635776,0.566816,0.588799,0.537415,0.585008,0.032600,19
16,0.037272,0.002150,0.014257,0.000164,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.731430,0.716349,0.686476,0.710172,0.613293,0.691544,0.041718,11
17,0.035839,0.003183,0.005594,0.001296,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.799185,0.786769,0.821307,0.810704,0.719528,0.787499,0.035885,8
18,0.039508,0.002895,0.008247,0.000740,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.232428,0.306815,0.236688,0.291707,0.346868,0.282901,0.043415,28
19,0.036805,0.002454,0.004961,0.000811,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.686126,0.598398,0.586104,0.573860,0.556109,0.600119,0.045217,13
20,0.036812,0.002415,0.013467,0.000492,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.732079,0.715992,0.686057,0.710177,0.613122,0.691485,0.041876,12
21,0.036920,0.001948,0.004442,0.000527,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.798212,0.787019,0.823118,0.810712,0.719979,0.787808,0.036003,7
22,0.039964,0.000964,0.007877,0.000774,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.248266,0.377692,0.315321,0.291779,0.346175,0.315846,0.044478,27
23,0.035872,0.003022,0.004199,0.000788,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.686126,0.598398,0.586104,0.573860,0.556109,0.600119,0.045217,13
24,0.039598,0.002035,0.013873,0.000669,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.788746,0.764261,0.818616,0.794131,0.709676,0.775086,0.036986,9
25,0.079968,0.034786,0.004909,0.000736,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.804603,0.784782,0.847674,0.807280,0.745448,0.797957,0.033268,4
26,0.039121,0.001887,0.007545,0.000911,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.656854,-0.432695,-0.346330,-0.484052,-0.076409,-0.399268,0.190629,38
27,0.044462,0.003029,0.004392,0.000817,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.669958,0.592446,0.586953,0.572862,0.556109,0.595666,0.039218,15
28,0.038799,0.002089,0.013748,0.000386,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.789144,0.764022,0.818319,0.794133,0.709586,0.775041,0.036992,10
29,0.097329,0.087764,0.004993,0.001311,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.804708,0.784713,0.847781,0.807295,0.745732,0.798046,0.033220,3
30,0.043494,0.001328,0.008367,0.001303,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.370980,-0.421011,-0.350248,-0.483750,-0.087414,-0.342681,0.135687,37
31,0.042806,0.003803,0.005026,0.000967,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.669958,0.592446,0.586953,0.572862,0.556109,0.595666,0.039218,15
32,0.046798,0.002204,0.014116,0.000391,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.795104,0.772917,0.846181,0.811601,0.725697,0.790300,0.040188,5
33,0.168473,0.137344,0.004997,0.000896,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.804915,0.783304,0.852190,0.810160,0.748175,0.799749,0.034104,2
34,0.041775,0.002356,0.007563,0.001034,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.795299,-1.629662,-1.461919,-1.712710,-0.929359,-1.505790,0.308601,39
35,0.056063,0.008919,0.004385,0.000634,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.669819,0.588893,0.587076,0.572849,0.557014,0.595130,0.039068,17
36,0.044776,0.002494,0.014544,0.000873,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.795353,0.772801,0.846034,0.811601,0.725615,0.790281,0.040189,6
37,0.087576,0.027472,0.004748,0.000684,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.805169,0.783163,0.852345,0.810160,0.748201,0.799808,0.034165,1
38,0.040540,0.002503,0.008362,0.001290,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.651895,-2.010670,-1.468842,-1.712109,-0.961821,-1.561068,0.346643,40
39,0.053919,0.009330,0.004580,0.000735,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.669819,0.588893,0.587076,0.572849,0.557014,0.595130,0.039068,17

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 43
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [16]:
Future_Preduction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Preduction={}".format(Future_Preduction))

Future_Preduction=[3316415.72004342]